version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
    ignore:
      # develocity-build-validation-scripts do not have semantic versioning
      - dependency-name: "*develocity-build-validation-scripts*"
