name: Run All Experiments

on:
  push:
    branches:
      - gf/fix-timeout-errors-concurrency-one
  workflow_dispatch:
  schedule:
    # Every Saturday at 09:00
    - cron: "0 9 * * 6"

jobs:

  androidx:
    uses: ./.github/workflows/run-experiments-androidx.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-beam:
    uses: ./.github/workflows/run-experiments-apache-beam.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-calcite:
    uses: ./.github/workflows/run-experiments-apache-calcite.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-geode:
    uses: ./.github/workflows/run-experiments-apache-geode.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-groovy:
    uses: ./.github/workflows/run-experiments-apache-groovy.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-james:
    uses: ./.github/workflows/run-experiments-apache-james.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-jmeter:
    uses: ./.github/workflows/run-experiments-apache-jmeter.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-kafka:
    uses: ./.github/workflows/run-experiments-apache-kafka.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-lucene:
    uses: ./.github/workflows/run-experiments-apache-lucene.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-ofbiz:
    uses: ./.github/workflows/run-experiments-apache-ofbiz.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-openwhisk:
    uses: ./.github/workflows/run-experiments-apache-openwhisk.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-samza:
    uses: ./.github/workflows/run-experiments-apache-samza.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apache-solr:
    uses: ./.github/workflows/run-experiments-apache-solr.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apereo-cas:
    uses: ./.github/workflows/run-experiments-apereo-cas.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  apollo-kotlin:
    uses: ./.github/workflows/run-experiments-apollo-kotlin.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  armeria:
    uses: ./.github/workflows/run-experiments-armeria.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  caffeine:
    uses: ./.github/workflows/run-experiments-caffeine.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  detekt:
    uses: ./.github/workflows/run-experiments-detekt.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  gradle:
    uses: ./.github/workflows/run-experiments-gradle.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  grails-core:
    uses: ./.github/workflows/run-experiments-grails-core.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  hibernate-orm:
    uses: ./.github/workflows/run-experiments-hibernate-orm.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  hibernate-search:
    uses: ./.github/workflows/run-experiments-hibernate-search.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  java-ordered-properties:
    uses: ./.github/workflows/run-experiments-java-ordered-properties.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  jhipster-sample:
    uses: ./.github/workflows/run-experiments-jhipster-sample.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  junit5:
    uses: ./.github/workflows/run-experiments-junit5.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  kotlin:
    uses: ./.github/workflows/run-experiments-kotlin.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micrometer:
    uses: ./.github/workflows/run-experiments-micrometer.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micronaut-aws:
    uses: ./.github/workflows/run-experiments-micronaut-aws.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micronaut-core:
    uses: ./.github/workflows/run-experiments-micronaut-core.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micronaut-data:
    uses: ./.github/workflows/run-experiments-micronaut-data.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micronaut-kafka:
    uses: ./.github/workflows/run-experiments-micronaut-kafka.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micronaut-kotlin:
    uses: ./.github/workflows/run-experiments-micronaut-kotlin.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micronaut-security:
    uses: ./.github/workflows/run-experiments-micronaut-security.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micronaut-spring:
    uses: ./.github/workflows/run-experiments-micronaut-spring.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  micronaut-starter:
    uses: ./.github/workflows/run-experiments-micronaut-starter.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  microstream:
    uses: ./.github/workflows/run-experiments-microstream.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  morphia:
    uses: ./.github/workflows/run-experiments-morphia.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  nokee:
    uses: ./.github/workflows/run-experiments-nokee.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  openapi-generator:
    uses: ./.github/workflows/run-experiments-openapi-generator.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  openrewrite:
    uses: ./.github/workflows/run-experiments-openrewrite.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  quarkus:
    uses: ./.github/workflows/run-experiments-quarkus.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  ratpack:
    uses: ./.github/workflows/run-experiments-ratpack.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  spock:
    uses: ./.github/workflows/run-experiments-spock.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  spring-amqp:
    uses: ./.github/workflows/run-experiments-spring-amqp.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  spring-authorization-server:
    uses: ./.github/workflows/run-experiments-spring-authorization-server.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  spring-boot:
    uses: ./.github/workflows/run-experiments-spring-boot.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  spring-framework:
    uses: ./.github/workflows/run-experiments-spring-framework.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  spring-kafka:
    uses: ./.github/workflows/run-experiments-spring-kafka.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  spring-security:
    uses: ./.github/workflows/run-experiments-spring-security.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  testcontainers:
    uses: ./.github/workflows/run-experiments-testcontainers.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  wrapper-upgrade-gradle-plugin:
    uses: ./.github/workflows/run-experiments-wrapper-upgrade-gradle-plugin.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

  xwiki:
    uses: ./.github/workflows/run-experiments-xwiki.yml
    secrets: inherit
    concurrency:
      group: ${{ github.ref }}

