name: Run All Experiments

on:
  push:
    branches:
      - gf/fix-timeout-errors-concurrency-one
  workflow_dispatch:
  schedule:
    # Every Saturday at 09:00
    - cron: "0 9 * * 6"

jobs:

  androidx:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-androidx.yml

  apache-beam:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-beam.yml

  apache-calcite:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-calcite.yml

  apache-geode:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-geode.yml

  apache-groovy:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-groovy.yml

  apache-james:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-james.yml

  apache-jmeter:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-jmeter.yml

  apache-kafka:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-kafka.yml

  apache-lucene:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-lucene.yml

  apache-ofbiz:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-ofbiz.yml

  apache-openwhisk:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-openwhisk.yml

  apache-samza:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-samza.yml

  apache-solr:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apache-solr.yml

  apereo-cas:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apereo-cas.yml

  apollo-kotlin:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-apollo-kotlin.yml

  armeria:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-armeria.yml

  caffeine:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-caffeine.yml

  detekt:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-detekt.yml

  gradle:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-gradle.yml

  grails-core:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-grails-core.yml

  hibernate-orm:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-hibernate-orm.yml

  hibernate-search:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-hibernate-search.yml

  java-ordered-properties:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-java-ordered-properties.yml

  jhipster-sample:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-jhipster-sample.yml

  junit5:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-junit5.yml

  kotlin:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-kotlin.yml

  micrometer:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micrometer.yml

  micronaut-aws:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micronaut-aws.yml

  micronaut-core:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micronaut-core.yml

  micronaut-data:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micronaut-data.yml

  micronaut-kafka:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micronaut-kafka.yml

  micronaut-kotlin:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micronaut-kotlin.yml

  micronaut-security:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micronaut-security.yml

  micronaut-spring:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micronaut-spring.yml

  micronaut-starter:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-micronaut-starter.yml

  microstream:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-microstream.yml

  morphia:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-morphia.yml

  nokee:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-nokee.yml

  openapi-generator:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-openapi-generator.yml

  openrewrite:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-openrewrite.yml

  quarkus:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-quarkus.yml

  ratpack:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-ratpack.yml

  spock:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-spock.yml

  spring-amqp:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-spring-amqp.yml

  spring-authorization-server:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-spring-authorization-server.yml

  spring-boot:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-spring-boot.yml

  spring-framework:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-spring-framework.yml

  spring-kafka:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-spring-kafka.yml

  spring-security:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-spring-security.yml

  testcontainers:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-testcontainers.yml

  wrapper-upgrade-gradle-plugin:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-wrapper-upgrade-gradle-plugin.yml

  xwiki:
    concurrency:
      group: ${{ github.ref }}
    uses: ./.github/workflows/run-experiments-xwiki.yml

