name: Quarkus

on:
  push:
    paths:
      - '.github/workflows/run-experiments-quarkus.yml'
  schedule:
    # Every Sunday at 6.00pm
    - cron: "0 18 * * 0"
  workflow_dispatch:

permissions:
  contents: read

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/quarkusio/quarkus"
  GOALS: "install"
  ARGS: "-B -Dquickly -T0.5C"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - experimentId: 1
          - experimentId: 2
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@ba34de01b7f4ba2ab8e2860df8993a29f4477056 # v1.20.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.9
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/download@94c54bdb1e6a57347930c62e9254d2c3e55fd5a5 # actions-stable
        with:
          downloadDevelopmentRelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure validation scripts network settings
        uses: gradle/develocity-oss-projects/.github/actions/configure-validation-scripts-network-settings@0bab5beea90a90c73dca0ce5a8fa75660860c84e # main
      - name: Run experiment 1
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-1@94c54bdb1e6a57347930c62e9254d2c3e55fd5a5 # actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
        if: matrix.experimentId == 1
      - name: Run experiment 2
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-2@94c54bdb1e6a57347930c62e9254d2c3e55fd5a5 # actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
        if: matrix.experimentId == 2
