name: Micronaut Spring

on:
  schedule:
    - cron: "0 2 * * 6"
  workflow_dispatch:

permissions:
  contents: read

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/micronaut-projects/micronaut-spring"
  TASKS: "check"
  # Excludes:
  # - :test-suite:test - https://ge.micronaut.io/scans/failures?failures.failureClassification=verification&failures.failureMessage=Execution%20failed%20for%20task%20%27:test-suite:test%27.%0A%3E%20Test%20process%20encountered%20an%20unexpected%20problem.%0A%20%20%20%3E%20Could%20not%20start%20Gradle%20Test%20Executor%20*%20Failed%20to%20load%20JUnit%20Platform.%20%20Please%20ensure%20that%20all%20JUnit%20Platform%20dependencies%20are%20available%20on%20the%20test%27s%20runtime%20classpath%2C%20including%20the%20JUnit%20Platform%20launcher.&search.rootProjectNames=spring-parent&search.timeZoneId=America%2FChicago
  ARGS: "-x :test-suite:test"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - experimentId: 1
          - experimentId: 2
          - experimentId: 3
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/download@actions-stable
        with:
          downloadDevelopmentRelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure validation scripts network settings
        uses: gradle/develocity-oss-projects/.github/actions/configure-validation-scripts-network-settings@main
      - name: Run experiment 1
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-1@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
        if: matrix.experimentId == 1
      - name: Run experiment 2
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-2@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
        if: matrix.experimentId == 2
      - name: Run experiment 3
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-3@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: false
        if: matrix.experimentId == 3
