name: Hibernate Search

on:
  schedule:
    - cron: "0 3 * * 4"
  workflow_dispatch:

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/hibernate/hibernate-search"
  GOALS: "install"
  ARGS: "-B -Pjqassistant -Pci-build -DskipITs"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - experimentId: 1
          - experimentId: 2
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/download@actions-stable
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run experiment 1
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-1@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
        if: matrix.experimentId == 1
      - name: Run experiment 2
        uses: gradle/develocity-build-validation-scripts/.github/actions/maven/experiment-2@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          goals: ${{ env.GOALS }}
          args: ${{ env.ARGS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
        if: matrix.experimentId == 2
