name: Spring Framework

on:
  schedule:
    # Every Sunday at 9.00am
    - cron: "0 9 * * 0"
  workflow_dispatch:

env:
  DEVELOCITY_URL: "https://ge.solutions-team.gradle.com"
  GIT_REPO: "https://github.com/spring-projects/spring-framework"
  TASKS: "build"

jobs:
  Experiment:
    strategy:
      fail-fast: false
      matrix:
        include:
          - experimentId: 1
          - experimentId: 2
          - experimentId: 3
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21 EA
        uses: actions/setup-java@v4
        with:
          java-version: 21-ea
          distribution: "temurin"
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
      - name: Download latest version of the validation scripts
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/download@actions-stable
        with:
          downloadDevelopmentRelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - working-directory: develocity-gradle-build-validation
        run: |
          sed -i 's/#connect.timeout=PT5S/connect.timeout=PT60S/g' network.settings
          sed -i 's/#read.timeout=PT30S/read.timeout=PT60S/g' network.settings
      - name: Run experiment 1
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-1@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
        if: matrix.experimentId == 1
      - name: Run experiment 2
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-2@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
        if: matrix.experimentId == 2
      - name: Run experiment 3
        uses: gradle/develocity-build-validation-scripts/.github/actions/gradle/experiment-3@actions-stable
        env:
          DEVELOCITY_ACCESS_KEY: "${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}"
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          develocityUrl: ${{ env.DEVELOCITY_URL }}
          failIfNotFullyCacheable: true
        if: matrix.experimentId == 3
